language: ruby

services:
  - docker

before_install:
  - docker --version
  - docker build -f Dockerfile.dev --tag roblobob/k8s-server-time-client-dev ./src/client
  - docker build -f Dockerfile.dev --tag roblobob/k8s-server-time-server-dev ./src/server

script:
  - docker run --rm roblobob/k8s-server-time-client-dev /bin/sh -c "cd /app; yarn test"
  - docker run --rm roblobob/k8s-server-time-server-dev /bin/sh -c "cd /app; yarn test"

after_success:
  - docker build --tag roblobob/k8s-server-time-client ./src/client
  - docker build --tag roblobob/k8s-server-time-server ./src/server
  
  # login to docker cli and push images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push roblobob/k8s-server-time-client
  - docker push roblobob/k8s-server-time-server
