dist: focal

language: python

services:
  - docker

before_install:
  - docker --version
  - docker build --tag roblobob/k8s-server-time-client-dev --file ./src/client/Dockerfile.dev ./src/client
  - docker build --tag roblobob/k8s-server-time-server-dev --file ./src/server/Dockerfile.dev ./src/server
  # digitalocean cli setup
  - sudo snap install doctl
  - sudo snap connect doctl:kube-config
  - sudo snap connect doctl:dot-docker

script:
  - docker run --rm roblobob/k8s-server-time-client-dev /bin/sh -c "cd /app; yarn test"
  - docker run --rm roblobob/k8s-server-time-server-dev /bin/sh -c "cd /app; yarn test"

after_success:
  - docker build --tag roblobob/k8s-server-time-client:$TRAVIS_COMMIT ./src/client
  - docker build --tag roblobob/k8s-server-time-server:$TRAVIS_COMMIT ./src/server

  # login to docker cli and push images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push roblobob/k8s-server-time-client:$TRAVIS_COMMIT
  - docker push roblobob/k8s-server-time-server:$TRAVIS_COMMIT
