version: "3.8"
services:
  client:
    build:
      context: src/client/
      dockerfile: Dockerfile.dev

    container_name: k8s-test-project-client
    ports: 
      - 1234:1234
    volumes:
      - ./src/client/src/:/app/src/
  
  server:
    build:
      context: src/server/
      dockerfile: Dockerfile.dev

    container_name: k8s-test-project-server
    ports:
      - 3000:3000
    volumes:
      - ./src/server/src/:/app/src/
