apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-servicea
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: 1.k8s.local
    http:
      paths:
      - path: /
        backend:
          serviceName: client-cluster-ip-service
          servicePort: 8080
      - path: /api/
        backend:
          serviceName: server-cluster-ip-service
          servicePort: 3000
